---
title: "Disclaimer"
output: html_document
---

## Authorship

This web-based service has been develop by the [Vegetation Modeling Group](http://vegmod.github.iu/)
at [Forest Sciences Centre of Catalonia (CTFC)](http://www.ctfc.cat),
in collaboration with the
[Center for Ecological Research and Forestry Applications (CREAF)](http://www.creaf.cat/):

  + *Idea and conceptual design*: Miquel de Cáceres (CTFC/CREAF), Víctor Granda (CTFC) & Antoine Cabon (CTFC/CREAF).
  
  + *Package development*: Miquel De Cáceres (CTFC/CREAF), Antoine Cabon (CTFC/CREAF), Nicolas Martin StPaul (INRA) & Víctor Granda (CTFC).
  
  + *User interface*: Víctor Granda (CTFC).
  
  + *Contact*: Miquel De Cáceres (miquelcaceres@gmail.com)

---

## Data sources

  + Information elaborated using daily weather data obtained from the
    [Agencia Estatal de Meteorologia (AEMET)](http://www.aemet.es).
    
  + Historic (1990-2015) weather data obtained from the
    [Agencia Estatal de Meteorologia (AEMET)](http://www.aemet.es) and
    [Servei Meteorologic de Catalunya (SMC)](http://www.meteo.cat).
  
  + Climate scenarios (2006-2100) downloaded from
    [Earth System Grid Federation (ESGF)](http://esgf.llnl.gov/).

---

## Funding projects

  + *Projects*: **INFORMED** (PCIN-2014-050), **FORESTCAST** (CGL2014-59742-C2-2-R,
    Ministerio de Economía y Competitividad), **DRESS** (CGL2017-89149-C2-2-R, Ministerio de Economía y Competitividad).

  + *Fellowships*: RYC-2012-11109 to M. De Cáceres (Ministerio de Economía y
    Ciencia).

---

## Disclaimer

The data offered in this website is the result of modelling exercises and the
accuracy of results may be impaired by several factors, like inaccuracies of
input data, inappropriate model design or parameterization. Users should be aware
of all these limitations when using the data offered here. We decline all
responsibility for how the data in this website is used by third parties.
